<a href="https://colab.research.google.com/github/sejallotliker/Numpy-Library-Udemy-course/blob/main/Numpy_Library_course_Udemy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy Library

It is numerical python which basically deals with numbers.

In [ ]:
import numpy as np
#help(np.array)

In [ ]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
c= np.array([1,2,3,4],'complex')
print(c)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


## Arange function


```
arange(start, stop, skip, dtype)
```
NumPy arange() is one of the array creation routines based on numerical ranges. It creates an instance of ndarray with evenly spaced values and returns the reference to it.


In [ ]:
#help(np.arange)

d= np.arange(1,7)
print(d)

[1 2 3 4 5 6]


In [ ]:
d= np.arange(12.0)
print(d)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


In [ ]:
d_1= np.arange(2, 20, 2)
print(d_1)
d_2= np.arange(10, dtype="complex")
print(d_2)

[ 2  4  6  8 10 12 14 16 18]
[0.+0.j 1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j 7.+0.j 8.+0.j 9.+0.j]


##zeros()

Returns a new array of given shape and type with zeros.

In [ ]:
#help(np.zeros)
p= np.zeros(10)
print(p)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
q= np.zeros(10, dtype='int')
print(q)

[0 0 0 0 0 0 0 0 0 0]


In [ ]:
#for 2-D array:
r = np.zeros((5,5))
print(r)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


##ones() 

Same as zeros()

Returns a new array of a given shape and data type where the element's value is set to 1

In [ ]:
#help(np.ones) 
my_var=np.ones(5)
print(my_var)

[1. 1. 1. 1. 1.]


##empty()

Returns a new array of a given shape and type with random values

In [ ]:
t= np.empty([6,3] ,dtype='int')
print(t)

[[     94566486068912        476741369971        489626271861]
 [       433791696995        498216206368        468151435365]
 [       476741369968        416611827826        450971566194]
 [       519691042924        502511173664        416611827822]
 [       416611827830        463856468073        420906795105]
 [       433791697004     406819302277120 8214565720364810240]]


##Linspace function

Linspace function return evenly spaced numbers over a specified interval.

In [ ]:
#help(np.linspace)
m_1= np.linspace(1,40, num=5)
print(m_1)

m_2= np.linspace(1,40, num=5, endpoint= False)
print(m_2)

[ 1.   10.75 20.5  30.25 40.  ]
[ 1.   8.8 16.6 24.4 32.2]


In [ ]:
m_2= np.linspace(1,40, num=8, dtype='int')
print(m_2)

[ 1  6 12 17 23 28 34 40]


In [ ]:
m_2= np.linspace(1,40, num=8, retstep=True)
print(m_2)

(array([ 1.        ,  6.57142857, 12.14285714, 17.71428571, 23.28571429,
       28.85714286, 34.42857143, 40.        ]), 5.571428571428571)


#Identity and eye function:

##Eye function:

It returns a 2D array, with 1's as diagonals and zeroes elsewhere

In [ ]:
#help(np.eye)


In [ ]:
a= np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
b= np.eye(4,5)
#b=np.eye(n,m)
#(n=no of rows, m= no of columns)
print(b)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


k=1 shifts the diagonal with 1 in the above diagonal.

k=-1 shifts the giagonal filled with one below the main diagonal

In [ ]:
c_1=np.eye(3,k=1)
print(c_1)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [ ]:
c_2=np.eye(3,k=-1)
print(c_2)

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [ ]:
d=np.eye(4, k=2, dtype='int')
print(d)

[[0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]]


##Identity function: 

The identity array is a square array with ones in its main diagonals.

An identity function returns the identity array.

In [ ]:
#help(np.identity)

In [ ]:
e= np.identity(5, dtype='int')
print(e)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


##Attributes of array:

In [ ]:
#----DIMENSIONS---
a= np.array([1,2,3,4,5])
#print(a.ndim)
b=np.array([[1,2],[3,4]])
print(b.ndim)

#----SHAPE----
#shape refers to the no of rows and the no of columns that your array is having.
variable = np.array([[1,2],[3,4]])
print(variable.shape)

#---- DATA TYPE ----
print(variable.dtype)

#------ITEM SIZE ----
print(variable.itemsize)

2
(2, 2)
int64
8


In [ ]:
v = np.array([[1,2],[3,4]])
print(v.itemsize)

8


##Indexing in the numpy Library:


In [ ]:
a= np.array([9,8,7,6,5])
print(a[1])
print(a)
print(a[0])
print(a[-5])

8
[9 8 7 6 5]
9
9


In [ ]:
b= np.array([[1,2],[3,4]])
print(b)
print(b[1][0])

[[1 2]
 [3 4]]
3


##Slicing in Numpy array

Slicing in numpy array is a process in which a sub array is obtained out of the main array.

In [ ]:
a= np.array([9,8,7,6,5])
print(a[0:3])
print(a[-4:-1])

[9 8 7]
[8 7 6]


In [ ]:
#Step function
print(a[0:6:2])

[9 7 5]


#Basic Arithmetic operations in array:

In [ ]:
a= np.arange(1,5) #please note that the last no will not be included
b= np.arange(5,9)
print(a)
print(a+2)
# ---Multiplication
print(a*6)
#subtraction of 5 from a
print(a-5)
#--- to add two arrays---
print(a+b)
#---exponent---
print(a**2)

[1 2 3 4]
[3 4 5 6]
[ 6 12 18 24]
[-4 -3 -2 -1]
[ 6  8 10 12]
[ 1  4  9 16]


In [ ]:
#2-D array
b= np.array([[5,6],[7,8]])
print(b)
print(b*2)

[[5 6]
 [7 8]]
[[10 12]
 [14 16]]


In [ ]:
p=np.arange(1,5)
q=np.array([5,6,7,8])
print(p+q)
print(p**q)
print(p*q)
print(p/q)

[ 6  8 10 12]
[    1    64  2187 65536]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


#Reshape and resize function:

#Reshape function:
### returns: a new shape to an array without changing its data

In [ ]:
import numpy as np
#help(np.reshape)
a=np.arange(10)
print(a)
print(a.shape)

b=np.reshape(a,(5,2))
print(b)
print(b.shape)



[0 1 2 3 4 5 6 7 8 9]
(10,)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
(5, 2)


In [ ]:
c=np.reshape(a, (5,2), order="F")
print(c)

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


##Resize function

In [ ]:
#help(np.resize)
a= np.arange(5)
print(a)
print(np.resize(a, (2,3)))


[0 1 2 3 4]
[[0 1 2]
 [3 4 0]]


#Flatten Function:

flatten() returns a copy of the array collapsed into 1 D

In [ ]:
import numpy as np
a= np.array([[1,2],[3,4]])
print(a)

print(a.flatten()) #converts 2D array into 1D array

[[1 2]
 [3 4]]
[1 2 3 4]


In [ ]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print(b.flatten()) #row wise
print(b.flatten(order="F")) #column wise

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[1 4 7 2 5 8 3 6 9]


#Ravel Function:
Used to change a 2D array or a multidimentional array into a contigous flatten function.
similar to flatten function

In [ ]:
#help(np.ravel)
a= np.array([[2,3],[4,5]])
print(a)
print(np.ravel(a))



[[2 3]
 [4 5]]
[2 3 4 5]


In [ ]:
b= np.array([[2,3,4],[5,6,7],[8,9,10]])
print(b)
print(np.ravel(b))


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
[ 2  3  4  5  6  7  8  9 10]


In [ ]:
print(np.ravel(b, order='F'))

[ 2  5  8  3  6  9  4  7 10]


#Transpose function

Transpose function changes the row elements into column elements and the column elements into row elements.


In [ ]:
#help(np.transpose)
a= np.arange(1,11).reshape(5,2)
print(a)
print(a.shape)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
(5, 2)


In [ ]:
print(np.transpose(a))
print(np.transpose(a).shape)

[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]
(2, 5)


In [ ]:
b= np.arange(1,25).reshape(2,3,4) #2--> no of arrays  #3--> no of rows  #4--> no of columns
print(b)
print(b.shape)


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
(2, 3, 4)


In [ ]:

print(np.transpose(b))
print(np.transpose(b).shape)

[[[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]

 [[ 4 16]
  [ 8 20]
  [12 24]]]
(4, 3, 2)


In [ ]:
#transpose function in 1D 
a= np.arange(10)
print(a)
print(np.transpose(a)) #there is no changes on 1 D array.

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
